{{ if eq .Values.enableSelfManagement true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # using a fixed name to avoid deploy the controplan with self management mutiple times
  name: open-cluster-management:multicluster-controlplane:self-management:agent-execution-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # The policy agent need cluster-admin permission to enforcing configuration policies.
  # TODO consider to use adim instead of cluster-admin, when user need some special permissions to deploy
  # their works or polices, user can escalate their permissions manually.
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: multicluster-controlplane-sa
  namespace: {{ .Release.Namespace }}
{{ end }}
