# Addition ClusterRole permission for registration agent
# Registration agent needs these permission to manage addons whose agents runs in managed cluster while registration 
# agent itself runs in the management cluster. For example, if klusterlet is deployed in hosted mode, but an addon is 
# deployed in default mode, then the registration agent runs outside the managed cluster and the addon agents run on 
# the managed cluster.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:{{ .KlusterletName }}:addon-management
rules:
# Allow agent to get/list/watch/create/delete/update/patch secrets.
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
# Allow agent to list addons lease
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "get", "list", "update", "watch", "patch"]
# Allow agent to manage build-in addons
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["clusterclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["config.openshift.io"]
  resources: ["infrastructures", "clusterversions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy.open-cluster-management.io"]
  resources: ["configurationpolicies", "policies"]
  verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
- apiGroups: ["policy.open-cluster-management.io"]
  resources: ["configurationpolicies/status", "policies/status"]
  verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
